### ISSUE TITLE
Bot thinks it's still playing a song even after being disconnected. The same song gets "played" until the bot restarts.

### ISSUE THREAD

**Issue by FlorianSchwarzl** [plastik-flasche/SUS-Bot#5]
# How to replicate

Simply start playing a song, then disconnect the bot forcefully. If you type !queue it still says it's playing the song, even hours or days later. The only way to get it to play something again is to type !stop or !leave, or by restarting it.

# Possible fix

Check if bot disconnects/if it's still connected and clear the queue

**Comment by roteKlaue** [comment]
i told u already that i'm working on it why u so mean

**Comment by roteKlaue** [comment]
fixed with new update
